model:
  type: VISION_CLS
  name: resnet20_cifar100
  params:
    pretrained: True
    num_classes: 100

training:
  criterion: CrossEntropyLoss
  optimizer: Adam
  learning_rate: 0.001
  max_epochs: 1500
  val_every_n_epochs: 2
  log_every_n_steps: 10
  loggers:
    WandbLogger:
      params:
        name: resnet20_cifar100-rniq
        note: "Sym KL loss"
 
  callbacks:
    NoiseEarlyStopping:
      params:
        monitor: Loss/Validation loss
        mode: min
        patience: 40
        min_delta: 0.005
    ModelCheckpoint:
      params:
        filename: rniq_checkpoint_rsnt20
    ReduceLrOnOutlier:
      params:
        reduce_scale: 8
    RandNoiseScale:
      params:
        reduce_scale: 2

data:
  dataset_name: CIFAR100_DALI
  batch_size: 3000
  num_workers: 10


quantization:
  name: RNIQQuant
  qscheme: 1 # 0 for per-tensor, 1 for per-channel
  act_bit: 4
  weight_bit: 4
  distillation: True
  excluded_layers:
    - 'features.init_block.conv'
    - 'output'
