model:
  type: VISION_CLS
  name: resnet18
  params:
    pretrained: True
    num_classes: 1000

training:
  criterion: CrossEntropyLoss
  optimizer: Adam
  learning_rate: 0.00001
  max_epochs: 40
  val_every_n_epochs: 1
  log_every_n_steps: 100
  loggers:
    WandbLogger:
      params:
        name: resnet18-rniq
        note: "Testing resnet-18 with sym KL loss"
 
  callbacks:
    LayersWidthVis:
      params: {}
    NoiseEarlyStopping:
      params:
        monitor: Loss/Base train loss
        mode: min
        patience: 10
        min_delta: 0.005
    ModelCheckpoint:
      params:
        filename: rniq_checkpoint_rsnt18
    ReduceLrOnOutlier:
      params:
        reduce_scale: 4
        lr_lim: 0.0003
    RandNoiseScale:
      params:
        reduce_scale: 2
        update_every: 20

data:
  dataset_name: IMAGENET
  data_dir: ./data/imagenet
  batch_size: 100
  num_workers: 8


quantization:
  name: RNIQQuant
  qscheme: 1 # 0 for per-tensor, 1 for per-channel
  act_bit: 4
  weight_bit: 4
  distillation: True
  distillation_loss: Symmetrical KL
  excluded_layers:
    - 'conv1'
    - 'fc'
