model:
  type: VISION_CLS
  name: resnet20_cifar10_new
  params:
    pretrained: True
    num_classes: 10

training:
  criterion: CrossEntropyLoss
  optimizer: RAdam
  learning_rate: 0.002
  max_epochs: 1000
  val_every_n_epochs: 2
  log_every_n_steps: 10
  loggers:
    WandbLogger:
      params:
        name: resnet20-rniq
        note: "Symmetrical KL"
  callbacks:
    LayersWidthVis:
      params: {}
    NoiseEarlyStopping:
      params:
        monitor: Metric/ns_Accuracy_top1
        mode: max
        patience: 50
        min_delta: 0.0001
    ModelCheckpoint:
      params:
        monitor: Metric/ns_Accuracy_top1
        mode: max
        filename: rniq_checkpoint-{epoch:02d}-"{Metric/top-1:.2f}"
    TemperatureScale:
      params:
        temp_delta: 0.002
        scale_lr: 1
        warmup: 1000
data:
  dataset_name: CIFAR10
  batch_size: 1000
  num_workers: 8


quantization:
  name: RNIQQuant
  qscheme: 1 # 0 for per-tensor, 1 for per-channel
  weight_bit: 1
  act_bit: 1
  distillation: True
  distillation_loss: Symmetrical KL
  freeze_batchnorm: False
  excluded_layers:
    - 'features.init_block.conv'
    - 'output'
  calibration:
    act_bit: 10
    weight_bit: 10

