model:
  type: VISION_CLS
  name: resnet20_cifar10_new
  params:
    pretrained: True
    num_classes: 10

training:
  criterion: CrossEntropyLoss
  optimizer: Adam
  learning_rate: 0.005
  max_epochs: 1000
  val_every_n_epochs: 2
  log_every_n_steps: 10
  loggers:
    WandbLogger:
      params:
        name: resnet20-rniq
        note: "Symmetrical KL"
  callbacks:
    LayersWidthVis:
      params: {}
    NoiseEarlyStopping:
      params:
        monitor: Metric/ns_Accuracy_top1
        mode: max
        patience: 10
        min_delta: 0.005
    ModelCheckpoint:
      params:
        monitor: Metric/ns_Accuracy_top1
        mode: max
        filename: rniq_checkpoint-{epoch:02d}-"{Metric/top-1:.2f}"
    TemperatureScale:
      params:
        scale: 3.e-4
        scale_lr: 0.99985
        warmup: 200
data:
  dataset_name: CIFAR10
  batch_size: 1000
  num_workers: 8


quantization:
  name: RNIQQuant
  qscheme: 1 # 0 for per-tensor, 1 for per-channel
  weight_bit: 1
  act_bit: 1
  distillation: False
  # distillation_loss: Symmetrical KL
  excluded_layers:
    - 'features.init_block.conv'
    - 'output'
