model:
  type: VISION_CLS
  name: resnet18
  params:
    pretrained: True
    num_classes: 1000

training:
  criterion: CrossEntropyLoss
  optimizer: Adam
  learning_rate: 0.001
  max_epochs: 40
  val_every_n_epochs: 1
  log_every_n_steps: 100
  loggers:
    WandbLogger:
      params:
        name: resnet18-rniq
        note: "Testing resnet-18 with sym KL loss"
 
  callbacks:
    ModelCheckpoint:
      params:
        monitor: Metric/ns_Accuracy_top1
        mode: max
        filename: rniq_checkpoint-{epoch:02d}-"{Metric/ns_Accuracy_top1:.2f}"
    TemperatureScale:
      params:
        scale_lr: 1
        warmup: 1000
    NoiseEarlyStopping:
      params:
        monitor: Metric/ns_Accuracy_top1
        mode: max
        patience: 50
        min_delta: 0.001

data:
  dataset_name: IMAGENET
  data_dir: ./data/imagenet
  batch_size: 1000
  num_workers: 8


quantization:
  name: RNIQQuant
  qscheme: 1 # 0 for per-tensor, 1 for per-channel
  act_bit: 4
  weight_bit: 4
  distillation: True
  distillation_loss: Symmetrical KL
  excluded_layers:
    - 'conv1'
    - 'fc'
